/** Path constants — no hard-coded URLs in components */
export const paths = {
  home: "/",
  login: "/login",
  register: "/register",
  forgotPassword: "/forgot-password",
  resetPassword: "/reset-password",
  placementTest: "/placement-test",
  pricing: "/pricing",
  dictionary: "/dictionary",
  checkout: (orderId: string) => `/checkout/${orderId}`,
  learn: {
    hub: "/learn",
    course: (id: string) => `/learn/courses/${id}`,
    lesson: (id: string) => `/learn/lessons/${id}`,
    lessonPreview: (id: string) => `/learn/lessons/${id}/preview`,
    lessonSpeaking: (id: string) => `/learn/lessons/${id}/speaking`,
    lessonVocabulary: (id: string) => `/learn/lessons/${id}/vocabulary`,
    lessonVocabularyFocus: (lessonId: string, vocabId: string) =>
      `/learn/lessons/${lessonId}/vocabulary?focus=${vocabId}`,
    lessonVocabularyFlashcards: (id: string) =>
      `/learn/lessons/${id}/vocabulary/flashcards`,
    lessonGrammar: (id: string) => `/learn/lessons/${id}/grammar`,
    lessonGrammarFocus: (lessonId: string, grammarId: string) =>
      `/learn/lessons/${lessonId}/grammar?focus=${grammarId}`,
    lessonOverview: (id: string) => `/learn/lessons/${id}/overview`,
    lessonDialogue: (id: string) => `/learn/lessons/${id}/dialogue`,
    lessonKanji: (id: string) => `/learn/lessons/${id}/kanji`,
    lessonKanjiFocus: (lessonId: string, kanjiId: string) =>
      `/learn/lessons/${lessonId}/kanji?focus=${kanjiId}`,
    miniTest: (lessonId: string) => `/learn/lessons/${lessonId}/mini-test`,
    kanjiHub: "/learn/kanji",
    kanjiCourse: (courseId: string) => `/learn/kanji/course/${courseId}`,
    kanjiHandbook: "/learn/kanji/handbook",
    kanaQuiz: "/learn/kana-quiz",
  },
  student: {
    dashboard: "/dashboard",
    review: "/review",
    reviewKanji: "/review/kanji",
    reviewVocabulary: "/review/vocabulary",
    reviewGrammar: "/review/grammar",
    aiSpeaking: "/ai-speaking",
    practice: "/practice",
    jlptSim: "/practice/jlpt",
    jlptExam: (examId: string) => `/practice/jlpt/${examId}`,
    ocr: "/ocr",
    community: "/community",
    studySets: "/community/study-sets",
    studySetCreate: "/community/study-sets/create",
    studySetDetail: (id: string) => `/community/study-sets/${id}`,
    studySetEdit: (id: string) => `/community/study-sets/${id}/edit`,
    communityCall: "/community/call",
    notebook: "/notebook",
    notebookDefault: "/notebook",
    notebookCollectedList: "/notebook/collected",
    notebookPersonal: (
      notebookId: string,
      type: "kanji" | "vocabulary" | "grammar",
    ) => `/notebook/collected/${notebookId}/${type}`,
    notebookPool: (pool: "learned" | "collected") =>
      pool === "collected" ? "/notebook/collected" : "/notebook/learned/kanji",
    notebookSection: (
      pool: "learned" | "collected",
      type: "kanji" | "vocabulary" | "grammar",
    ) => `/notebook/${pool}/${type}`,
    notebookLearned: (type: "kanji" | "vocabulary" | "grammar") =>
      `/notebook/learned/${type}`,
    notebookCollected: (type: "kanji" | "vocabulary" | "grammar") =>
      `/notebook/collected/${type}`,
    jlptHistory: "/insights/jlpt-history",
    mistakes: "/insights/mistakes",
    feedback: "/feedback",
    feedbackDetail: (id: string) => `/feedback/${id}`,
  },
  admin: {
    dashboard: "/admin",
    kanji: "/admin/kanji",
    radicals: "/admin/radicals",
    vocabulary: "/admin/vocabulary",
    grammar: "/admin/grammar",
    courses: "/admin/courses",
    courseDetail: (courseId: string) => `/admin/courses/${courseId}`,
    lessonDetail: (courseId: string, lessonId: string) =>
      `/admin/courses/${courseId}/lessons/${lessonId}`,
    conversations: "/admin/conversations",
    mockExams: "/admin/mock-exams",
    mockExamDetail: (examId: string) => `/admin/mock-exams/${examId}`,
    questions: "/admin/questions",
    studySets: "/admin/study-sets",
    studySetDetail: (id: string) => `/admin/study-sets/${id}`,
    users: "/admin/users",
    config: "/admin/config",
    pricing: "/admin/pricing",
    reports: "/admin/reports",
    feedbacks: "/admin/feedbacks",
    feedbackDetail: (id: string) => `/admin/feedbacks/${id}`,
    analytics: "/admin/analytics",
  },
} as const;
