/** Path constants — no hard-coded URLs in components */
export const paths = {
  home: "/",
  login: "/login",
  register: "/register",
  placementTest: "/placement-test",
  learn: {
    hub: "/learn",
    course: (id: string) => `/learn/courses/${id}`,
    lesson: (id: string) => `/learn/lessons/${id}`,
    lessonSpeaking: (id: string) => `/learn/lessons/${id}/speaking`,
    lessonVocabulary: (id: string) => `/learn/lessons/${id}/vocabulary`,
    lessonGrammar: (id: string) => `/learn/lessons/${id}/grammar`,
    lessonDialogue: (id: string) => `/learn/lessons/${id}/dialogue`,
    lessonKanji: (id: string) => `/learn/lessons/${id}/kanji`,
    miniTest: (lessonId: string) => `/learn/lessons/${lessonId}/mini-test`,
    kanjiHub: "/learn/kanji",
    kanjiCourse: (courseId: string) => `/learn/kanji/course/${courseId}`,
    kanjiHandbook: "/learn/kanji/handbook",
  },
  student: {
    dashboard: "/dashboard",
    review: "/review",
    reviewKanji: "/review/kanji",
    reviewVocabulary: "/review/vocabulary",
    reviewGrammar: "/review/grammar",
    aiSpeaking: "/ai-speaking",
    practice: "/practice",
    jlptSim: "/practice/jlpt",
    ocr: "/ocr",
    community: "/community",
    studySets: "/community/study-sets",
    communityCall: "/community/call",
    /** @deprecated use learn.kanjiHandbook */
    notebook: "/learn/kanji/handbook",
  },
  admin: {
    dashboard: "/admin",
    kanji: "/admin/kanji",
    radicals: "/admin/radicals",
    vocabulary: "/admin/vocabulary",
    grammar: "/admin/grammar",
    courses: "/admin/courses",
    courseDetail: (courseId: string) => `/admin/courses/${courseId}`,
    lessonDetail: (courseId: string, lessonId: string) =>
      `/admin/courses/${courseId}/lessons/${lessonId}`,
    conversations: "/admin/conversations",
    questions: "/admin/questions",
    studySets: "/admin/study-sets",
    users: "/admin/users",
    config: "/admin/config",
  },
} as const;
